AT: method
log_dir: trained_models/cifar10
data_dir: ../dataset_data
pre_resume_path: trained_models/cifar10/mt_wrn-28-10_cifar10_seed1/state-last.pt

data: cifar10
augment: base
take_amount: 4000
unsup_fraction: 0.92
validation: true
batch_size: 128
batch_size_validation: 128
#seed: 1

#model: wrn-28-10
num_adv_epochs: 100
lr: 0.1
scheduler: cosinew

beta: 5.0
consistency_cost: 0
tau: 0.995
tau_after: 0.995
beta2: 0.05