AT: method
log_dir: trained_models/imagenet32
data_dir: ../dataset_data
pre_resume_path: trained_models/imagenet32/mt_wrn-28-10_imagenet32_seed1/state-last.pt

data: imagenet32
augment: base
take_amount: 10000
unsup_fraction: 0.92
validation: true
batch_size: 128
batch_size_validation: 128
#seed: 1

#model: wrn-28-10
num_adv_epochs: 100
lr: 0.1
scheduler: cosinew

beta: 1.0
consistency_cost: 0
tau: 0.995
tau_after: 0.995
out_feat: true
out_feat_dim: 256
beta2: 0.3


