method: wscat
pre_resume_path: trained_models/DATAINFO/mt_MODELINFO_SEEDINFO/state-last.pt

lamb: 1.0
consistency_cost: 0
tau: 0.995
tau_after: 0.995
beta: 0.05

data: cifar100
augment: base
take_amount: 10000
unsup_fraction: 0.8
validation: true
batch_size: 128
batch_size_validation: 128
num_adv_epochs: 100
lr: 0.1
scheduler: cosinew